iplug add https://github.com/pearofducks/ansible-vim
iplug add https://github.com/chrisbra/csv.vim
iplug add https://github.com/fatih/vim-go
iplug add https://github.com/robbles/logstash.vim
iplug add https://github.com/shime/vim-livedown
iplug add https://github.com/gpanders/vim-medieval
iplug add https://github.com/jmcantrell/vim-virtualenv
iplug add https://github.com/Vimjas/vim-python-pep8-indent
iplug add https://github.com/davidhalter/jedi-vim
iplug add https://github.com/rodjek/vim-puppet
iplug add https://github.com/rust-lang/rust.vim
iplug add https://github.com/racer-rust/vim-racer
iplug add https://github.com/towolf/vim-helm
iplug add https://github.com/mtdl9/vim-log-highlighting
iplug add https://github.com/hashivim/vim-terraform
iplug add https://github.com/sukima/xmledit
iplug add https://github.com/KeitaNakamura/neodark.vim
iplug add https://github.com/itchyny/lightline.vim
iplug add https://github.com/junegunn/fzf
iplug add https://github.com/junegunn/fzf.vim
iplug add https://github.com/preservim/nerdtree
iplug add https://github.com/Xuyuanp/nerdtree-git-plugin
iplug add https://github.com/liuchengxu/vim-which-key
iplug add https://github.com/nathanaelkane/vim-indent-guides
iplug add https://github.com/junegunn/goyo.vim
iplug add https://github.com/junegunn/limelight.vim
iplug add https://github.com/christoomey/vim-tmux-navigator
iplug add https://github.com/benmills/vimux
iplug add https://github.com/djoshea/vim-autoread
iplug add https://github.com/w0rp/ale
iplug add https://github.com/maralla/completor.vim
iplug add https://github.com/kana/vim-textobj-user
iplug add https://github.com/bps/vim-textobj-python
iplug add https://github.com/kana/vim-textobj-indent
iplug add https://github.com/glts/vim-textobj-comment
iplug add https://github.com/junegunn/vim-easy-align
iplug add https://github.com/brooth/far.vim
iplug add https://github.com/tpope/vim-surround
iplug add https://github.com/easymotion/vim-easymotion
iplug add https://github.com/vimwiki/vimwiki
